### PR TITLE
.net 8 migration

### LINKED ISSUE #346: Support for .NET 8 (RC1)
### Issue
When I upgrade to .NET 8 RC 1 (including Entity Framework Core), I get a `MissingMethodException` for `System.Collections.Generic.IEnumerable1<Microsoft.EntityFrameworkCore.Metadata.IProperty> Microsoft.EntityFrameworkCore.Metadata.IEntityType.GetProperties()`. This is because it was moved to `ITypeBase` (parent of `IEntityType`).
https://github.com/dotnet/efcore/blob/77a996f6403526d879e111421e40f72ad26d696b/src/EFCore/Metadata/ITypeBase.cs#L113-L114

### ~~Expectation~~ Hope
I know that EF Core 8 is still RC, but could you check if a version of Linq2db compiled against 8 RC1 is feasible?

### Exception
```
System.MissingMethodException : Method not found: 'System.Collections.Generic.IEnumerable`1<Microsoft.EntityFrameworkCore.Metadata.IProperty> Microsoft.EntityFrameworkCore.Metadata.IEntityType.GetProperties()'.

<>c.<DefineConvertors>b__14_0(IEntityType e)
SelectManySingleSelectorIterator`2.MoveNext()
HashSet`1.UnionWith(IEnumerable`1 other)
HashSet`1.ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
DistinctIterator`1.ToArray()
LinqToDBForEFToolsImplDefault.DefineConvertors(MappingSchema mappingSchema, IModel model, IValueConverterSelector convertorSelector, DataOptions dataOptions)
LinqToDBForEFToolsImplDefault.CreateMappingSchema(IModel model, IMetadataReader metadataReader, IValueConverterSelector convertorSelector, DataOptions dataOptions)
<>c__DisplayClass17_0.<GetMappingSchema>b__0(ICacheEntry e)
CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
LinqToDBForEFToolsImplDefault.GetMappingSchema(IModel model, IMetadataReader metadataReader, IValueConverterSelector convertorSelector, DataOptions dataOptions)
LinqToDBForEFTools.GetMappingSchema(IModel model, IInfrastructure`1 accessor, DataOptions dataOptions)
LinqToDBForEFTools.CreateLinqToDBConnection(DbContext context, IDbContextTransaction transaction)
...
```

### PR DESCRIPTION
**Pull request by MaceWindu**
Fix #346

Contains mostly styling changes for new VS/C# version. I will comment on functional changes

- [x] sqlite: ~integer autoincrement keys doesn't work~ fixed
- [x] mysql: ~several tests doesn't work due to changes to provider. [Issue](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1801). For now we will ignore exception, but it will prevent users from use of MySql provider extensions~ fixed
- [x] npgsql: works with linq2db 5.3.1 update to support npgsql 8
- [x] sqlserver: works

### CODE REVIEW

File: Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs [hunk 1]
```diff
@@ -462,7 +462,7 @@ public SqlTransparentExpression(Expression expression, RelationalTypeMapping? ty
 
 			protected override void Print(ExpressionPrinter expressionPrinter)
 			{
-				expressionPrinter.Print(Expression);
+				expressionPrinter.PrintExpression(Expression);
```
Comment (MaceWindu) [inline Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs:465]: change 1: api change on EF side

File: Source/LinqToDB.EntityFrameworkCore/Internal/EFCoreExpressionAttribute.cs [hunk 2]
```diff
@@ -10,7 +10,7 @@ namespace LinqToDB.EntityFrameworkCore.Internal
 	/// <summary>
 	/// Maps Linq To DB expression.
 	/// </summary>
-	public class EFCoreExpressionAttribute : Sql.ExpressionAttribute
+	public sealed class EFCoreExpressionAttribute : Sql.ExpressionAttribute
```
Comment (MaceWindu) [inline Source/LinqToDB.EntityFrameworkCore/Internal/EFCoreExpressionAttribute.cs:13]: change 2: sealed attribute, remove if we expect it to be redefined

**Comment by MaceWindu** [comment]
Classic :-/  :amu

6a91d394ddaef4c0b5f931e31847f0bf

**Review by sdanyliv — APPROVED** [review]
