### PR TITLE
Fixed SO when correcting ExpressionTree.

### LINKED ISSUE #108: Creating TempTable with custom name causes endless loop
Hi, 

I am attempting to create a temp table with Linq2db using a custom table name. Providing the table name parameter causes the library to enter an internal endless loop and the table never gets created. Eventually a stack overflow error occurs (with no stack trace). If the ```tableName``` parameter is omitted, the table is created successfully.

### Steps to reproduce

Attempting to execute this line of code causes the endless loop and the line never completes.

```c#
var table = connection.CreateTempTable(source, tableName: "#TestTable");
```

Excluding the name parameter causes the code to complete as normal:

```c#
var table = connection.CreateTempTable(source);
```

I created a repo that reproduces the issue [here](https://github.com/NWhittle/Linq2DbTempTableTests). 

### Environment details
linq2db version: 3.2.3
Database Server: Sqlite, SqlServer (doesn't seem to matter)
Database Provider: EF Core (via Linq2db.EntityFrameworkCore)
Operating system: Windows 10
.NET Framework: .NET Core 3.1

### PR DESCRIPTION
**Pull request by sdanyliv**
Fixes #108

### CODE REVIEW

File: Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs [hunk 1]
```diff
@@ -771,7 +772,7 @@ TransformInfo LocalTransform(Expression e)
 				{
 					case ExpressionType.Constant:
 					{
-						if (typeof(EntityQueryable<>).IsSameOrParentOf(e.Type) || typeof(DbSet<>).IsSameOrParentOf(e.Type))
+						if (typeof(EntityQueryable<>).IsSameOrParentOf(e.Type) || typeof(DbSet<>).IsSameOrParentOf(e.Type) || typeof(DbSet<>).IsSameOrParentOf(e.Type))
```
Comment (Shane32) [inline Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs:775]: Added code is duplicate of preceding type check.
